#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: 39.105.156.133
    port: 6379
    password: 123456
    database: 7
    ssl: false
  datasource:
    # MySql
    url: jdbc:mysql://39.105.156.133:3306/smartx_tax?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: mjprompt_chatpro
    password: DGhMFw7cGB7YjK7f
#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888

#smart配置
smart:
  #分布式锁配置
  lock:
    ##是否启用分布式锁
    enabled: false
    ##redis服务地址
    address: redis://127.0.0.1:6379
  #本地文件上传
  file:
    remote-mode: true
    upload-domain: http://localhost:8999
    remote-path: /usr/share/nginx/html
